baseURL = "https://daozi.art"
port = 8080
title = "机械臂 AI 智能绘画"
theme = "hugo-product-launch"

#themesDir = "../.."
languageCode = "zh-cn"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false




# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]


# The name of this wonderful theme ;-).

# The "title" of your website

# Render line-breaks in .md-files as line-breaks in HTML.
# This is e.g. useful for rendering a multi-line address.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true


[params]
   [params.logo]
    main = "images/logo3.png"
    alt = "Daozi Logo"
    size = "w-42 h-14"
   # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Builders Of The Future, Inc."

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "You don't even know what we can do for you!"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
    favicon = "images/favicon.png"

    showBlog = true
    mainSections = ['blog']
    googleFonts = true

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/share-image.png"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Builders Of The Future, Inc."

    # LICENSE: Hugo Product Launch by Jan Raasch is licensed
    # under Attribution 4.0 International (CC BY 4.0).
    # See https://github.com/janraasch/hugo-product-launch#license.
    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # **If** you would like to use this theme without attribution,
    # permissions beyond this license's scope **are available** at
    # https://github.com/janraasch/hugo-product-launch/blob/master/MORE_PERMISSIONS.md
    # hidedesignbyline = true

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"


[menu]

  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 3


  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2